configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82265842acr.azurecr.io/cloud-sample #내가 생성한 ACR 입력
  newTag: "202408120727"